#=========================================================================
# Design RTL node
#=========================================================================

name: design-rtl

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

outputs:
  - design.v
  - design_macro.v
  # synopsys dc read_design.tcl modification
  - read-design.tcl
 
#-------------------------------------------------------------------------
# Commands
#------------------------------------------------------------------------- 
  
commands:
  - cp ../../../caravel/verilog/rtl/defines.v outputs/design.v
  - cat ../../../verilog/rtl/user_project_wrapper.v >> outputs/design.v
  # fix all default_nettype non compiler directives
  - sed -i "s/default_nettype none/default_nettype wire/g" outputs/design.v
  # Copy GL netlist
  - cp ../../../verilog/gl/user_proj_example.v outputs/design_macro.v
